
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Renzo Costanzo
 */
public class Sortear extends javax.swing.JDialog {

    /**
     * Creates new form Sortear
     */
    conexion ne=new conexion();
    Connection con=ne.Conectar();
    int n=0,cedulaganador,cant;
    ArrayList aIDS = new ArrayList();
    ArrayList aCI = new ArrayList();
    public Sortear(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("SORTEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        n++;
        if(n==1){
        int cantidad=0,ii=3;
        String ganado="insert into ganador(cedula_ganador,id_ganador) values(?,?)",sq="SELECT * FROM comentarios ORDER BY rand() LIMIT "+cantidad;
        
        Statement st;
        //CONSEGUIR IDS DE PREMIOS
        try {
            Statement pst=con.createStatement();
            ResultSet rs = pst.executeQuery("select id from premios");
            
            
            while(rs.next()){
                cantidad++;
                aIDS.add(rs.getInt("id"));
            }
            //JOptionPane.showMessageDialog(null, cantidad);

            //String sq="SELECT * FROM comentarios ORDER BY rand() LIMIT "+cantidad;
            
            
            /*for(int u=0;u<aIDS.size();u++){
            JOptionPane.showMessageDialog(null, aIDS.get(u));
            }*/
            
            //JOptionPane.showMessageDialog(null, "SE ASIGNARON LOS GANADORES");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al conseguir ids" +ex);
        }
        //CONSEGUIR CEDULA DE GANADORES
        try {
            Statement pstg=con.createStatement();
            ResultSet rsg = pstg.executeQuery("SELECT cedula FROM concursantes ORDER BY rand() LIMIT "+cantidad+"");
            
            
            while(rsg.next()){
                aCI.add(rsg.getInt("cedula"));
            }
            
            //String sq="SELECT * FROM comentarios ORDER BY rand() LIMIT "+cantidad;
            
            
            /*for(int u=0;u<aCI.size();u++){
            JOptionPane.showMessageDialog(null, aCI.get(u));
            }*/
            
            //JOptionPane.showMessageDialog(null, "SE ASIGNARON LOS GANADORES");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al conseguir cedula de ganadores" +ex);
        }
        //ASIGNAR GANADOR EN LA BD
        for(int i=0;i<cantidad;i++){
        try{
            PreparedStatement pst2=con.prepareStatement("insert into ganadores(cedula_ganador,id_ganador) values(?,?)");
            
            pst2.setInt(1, (int) aCI.get(i));
            pst2.setInt(2, (int) aIDS.get(i));
            
            
           
            int vus=pst2.executeUpdate();
            if (vus>0){
                JOptionPane.showMessageDialog(null, "GANADOR '"+aCI.get(i)+"' INGRESADO CORRECTAMENTE");
            }
            
            
        }catch(SQLException ee){
            JOptionPane.showMessageDialog(null, "ERROR AL INGRESAR GANADORES, O \n O LOS GANADORES YA ESTA REGISTRADOS");
        }
        }
        }
        else{
            JOptionPane.showMessageDialog(null, "Ya se realizo un sorteo");
        }
                
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sortear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sortear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sortear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sortear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Sortear dialog = new Sortear(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
